version: "3.7"

services:
  ukulele:
    # image: ghcr.io/jocull/ukulele:jda-5
    build: ./
    restart: unless-stopped
    environment:
      CONFIG_DATABASE: ./db/database # Database location overwrite so mounting works
    volumes:
      - ./ukulele.yml:/opt/ukulele/ukulele.yml
      - ./db:/opt/ukulele/db
